# Generated by Django 5.1.3 on 2024-11-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0002_roombooking_email_roombooking_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
